name: Build and Publish NuGet package

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: NUGET_API_KEY
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v*}" >> $GITHUB_ENV
        
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          
      - name: Build
        run: dotnet build --configuration Release /p:Version=${{env.tag}}
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{env.tag}} --no-build --output .
      - name: Push
        run: dotnet nuget push /home/runner/work/active-directory-manager/active-directory-manager/ActiveDirectoryManager.${{env.tag}}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}